---

server:
  port: 48091

application:
  percentile:
    first: 25
    second: 50
    third: 75

spring:
  data:
    mongodb:
      username: admin
      password: pswrd
      host: localhost
      port: 27017
      database: synergetica-test
      authentication-database: admin

---

spring:
  profiles: docker
  data:
    mongodb:
      host: mongodatabase2
      port: 27017